import logging
import json

import google.generativeai as genai
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from config import settings

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="KUMO AI Detection Service")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

_gemini_configured = False


def _ensure_configured():
    global _gemini_configured
    if not _gemini_configured and settings.GEMINI_API_KEY:
        genai.configure(api_key=settings.GEMINI_API_KEY)
        _gemini_configured = True


class DetectRequest(BaseModel):
    code: str
    language: str = "unknown"


class DetectResponse(BaseModel):
    is_ai_generated: bool
    confidence: float
    reasoning: str


SYSTEM_PROMPT = """\
You are an expert code analyst for a university coding lab platform.
Your task is to determine whether a given snippet of code was generated by an AI assistant or handwritten by a human student.

Analyze the code for:
- Overly generic variable names and algorithmic structures typical to LLMs.
- Lack of human-like idiosyncrasies or organic errors.
- Typical boilerplate and comments often included by AI models.

You must output your analysis in strict JSON format matching the schema:
{
  "is_ai_generated": true/false,
  "confidence": 0.0 to 1.0,
  "reasoning": "Detailed explanation of your reasoning"
}

Code Language: {language}
"""


@app.get("/")
async def health_check():
    return {"status": "online", "service": "ai-detection"}


@app.post("/detect", response_model=DetectResponse)
async def detect_ai_code(req: DetectRequest):
    if not settings.GEMINI_API_KEY:
        raise HTTPException(status_code=500, detail="Gemini API Key is not configured")

    _ensure_configured()

    try:
        model = genai.GenerativeModel(
            "gemini-2.5-flash",
            system_instruction=SYSTEM_PROMPT.format(language=req.language),
            generation_config={"response_mime_type": "application/json"},
        )
        response = model.generate_content(req.code)

        if not response.text:
            raise Exception("Empty response from model")

        result = json.loads(response.text)

        return DetectResponse(
            is_ai_generated=bool(result.get("is_ai_generated", False)),
            confidence=float(result.get("confidence", 0.0)),
            reasoning=str(result.get("reasoning", "No reasoning provided.")),
        )

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse JSON response: {e}", exc_info=True)
        raise HTTPException(
            status_code=500, detail="Failed to parse analysis response from model."
        )
    except Exception as e:
        logger.error(f"Detection failed: {e}", exc_info=True)
        raise HTTPException(
            status_code=500, detail=f"Failed to analyze code: {str(e)}"
        )
